export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';

export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';

export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';

export const TOURNAMENTS_LOADING = 'TOURNAMENTS_LOADING';