// Tournament CRUD
export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const TOURNAMENTS_LOADING = 'TOURNAMENTS_LOADING';
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';
export const ADD_TOURNAMENT_FAIL = 'ADD_TOURNAMENT_FAIL'
export const EDIT_TOURNAMENT = 'EDIT_TOURNAMENT';
export const EDIT_TOURNAMENT_FAIL = 'EDIT_TOURNAMENT_FAIL';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const SHOW_TOURNAMENT = 'SHOW_TOURNAMENT';
export const TOURNAMENT_LOADING = 'TOURNAMENT_LOADING';

// User Authentication && CRUD
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_DETAILS_FAILED = 'UPDATE_DETAILS_FAILED';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// Error Handling
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Registered Players
export const GET_PLAYERS = 'GET_PLAYERS';
export const PLAYERS_LOADING = 'PLAYERS_LOADING';
export const SHOW_PLAYER = 'SHOW_PLAYER';
export const PLAYER_LOADING = 'PLAYER_LOADING';

// Tournament Functionality
export const USER_JOINS_TOURNAMENT = 'USER_JOINS_TOURNAMENT';
export const TOURNAMENT_SIGN_UP_FAIL = 'TOURNAMENT_SIGN_UP_FAIL';
export const TOURNAMENT_STATUS_UPDATE = 'TOURNAMENT_STATUS_UPDATE';
export const TOURNAMENT_STATUS_FAILED = 'TOURNAMENT_STATUS_FAILED';
export const SHUFFLE_PARTICIPANTS = 'SHUFFLE_PARTICIPANTS';
export const SHUFFLE_FAILED = 'SHUFFLE_FAILED';
export const SET_CHAMPION = 'SET_CHAMPION';
export const SET_CHAMPION_FAILED = 'SET_CHAMPION_FAILED';

// Bracket Functionality
export const ADD_ROUND = 'ADD_ROUND';
export const ADD_ROUND_FAILED = 'ADD_ROUND_FAILED';
export const MATCHWINS_UPDATE = 'MATCHWINS_UPDATE';
export const MATCHWINS_UPDATE_FAILED = 'MATCHWINS_UPDATE_FAILED';

// Admin action
export const DELETE_A_USER = 'DELETE_A_USER';