export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const TOURNAMENTS_LOADING = 'TOURNAMENTS_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

export const GET_FIGHTERS = 'GET_FIGHTERS';
export const FIGHTERS_LOADING = 'FIGHTERS_LOADING';

export const USER_JOINS_TOURNAMENT = 'USER_JOINS_TOURNAMENT';
export const TOURNAMENT_SIGN_UP_FAIL = 'TOURNAMENT_SIGN_UP_FAIL';

export const TOURNAMENT_LOADING = 'TOURNAMENT_LOADING';
export const SHOW_TOURNAMENT = 'SHOW_TOURNAMENT';